<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CatchupService.Worker-307cc57c-bdc2-410b-91c5-408ef366a05c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="Always" />
    <None Update="nlog.config" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SubscriptionService.Application\SubscriptionService.Application.csproj" />
    <ProjectReference Include="..\SubscriptionService.Domain\SubscriptionService.Domain.csproj" />
    <ProjectReference Include="..\SubscriptionService.Infrastructure\SubscriptionService.Infrastructure.csproj" />
  </ItemGroup>
</Project>
