// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubscriptionService.Infrastructure.Persistence;

#nullable disable

namespace CatchupService.Infrastructure.Migrations
{
    [DbContext(typeof(CatchupServiceDbContext))]
    partial class CatchupServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.BuiltInIndexCatalogEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("LastSeenCommitPosition")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Name");

                    b.ToTable("BuiltInIndexCatalog", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.DailyCommitPositionEntity", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecondaryIndexName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CommitPosition")
                        .HasColumnType("bigint");

                    b.HasKey("SubscriptionId", "SecondaryIndexName", "Date");

                    b.ToTable("DailyCommitPositions", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.EndpointEntity", b =>
                {
                    b.Property<int>("EndpointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EndpointId"));

                    b.Property<string>("AuthenticationParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthenticationScheme")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("EndpointId");

                    b.ToTable("Endpoints", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.IndexScanStateEntity", b =>
                {
                    b.Property<string>("SecondaryIndexName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("LastScannedCommitPosition")
                        .HasColumnType("bigint");

                    b.HasKey("SecondaryIndexName");

                    b.ToTable("IndexScanStates", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.ParkedEventEntity", b =>
                {
                    b.Property<Guid>("ParkedEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ParkedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ParkedEventId");

                    b.HasIndex("SubscriptionId", "SequenceNumber");

                    b.ToTable("ParkedEvents", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.ReplaySessionEntity", b =>
                {
                    b.Property<Guid>("ReplaySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ReplaySessionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("ReplaySessions", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.StreamEventCountEntity", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("LastScannedCommitPosition")
                        .HasColumnType("bigint");

                    b.Property<string>("SecondaryIndexName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TotalCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SubscriptionId");

                    b.ToTable("StreamEventCounts", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.SubscriptionCheckpointEntity", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CheckpointReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("CommitPosition")
                        .HasColumnType("bigint");

                    b.Property<long?>("PreparePosition")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("SubscriptionId");

                    b.ToTable("SubscriptionCheckpoints", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.SubscriptionConfigurationEntity", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CheckpointBatchSize")
                        .HasColumnType("int");

                    b.Property<bool>("ContinueOnParked")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableEventLogging")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("EndpointId")
                        .HasColumnType("int");

                    b.Property<string>("OperationalReason")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OperationalState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("RequestTimeoutSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("RetryDelaySeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("RetryMaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryIndexName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("SoftDeleteParked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("EndpointId");

                    b.ToTable("SubscriptionConfigurations", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.SubscriptionEventLogEntity", b =>
                {
                    b.Property<long>("SubscriptionEventLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AddressSentTo")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("DeliveryAttempt")
                        .HasColumnType("int");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsReplay")
                        .HasColumnType("bit");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubscriptionEventLogId");
                    b.HasIndex("SubscriptionId", "ProcessedAt");
                    b.ToTable("SubscriptionEventLogs", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.SubscriptionConfigurationEntity", b =>
                {
                    b.HasOne("CatchupService.Infrastructure.Persistence.EndpointEntity", "Endpoint")
                        .WithMany("Subscriptions")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.EndpointEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
