// <auto-generated />
using System;
using CatchupService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatchupService.Infrastructure.Migrations
{
    [DbContext(typeof(CatchupServiceDbContext))]
    [Migration("20260603162915_additional_config_options")]
    partial class additional_config_options
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.ParkedEventEntity", b =>
                {
                    b.Property<Guid>("ParkedEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ParkedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ParkedEventId");

                    b.HasIndex("SubscriptionId", "SequenceNumber");

                    b.ToTable("ParkedEvents", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.ReplaySessionEntity", b =>
                {
                    b.Property<Guid>("ReplaySessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ReplaySessionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("ReplaySessions", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.SubscriptionCheckpointEntity", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Checkpoint")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommitPosition")
                        .HasColumnType("bigint");

                    b.HasKey("SubscriptionId");

                    b.ToTable("SubscriptionCheckpoints", (string)null);
                });

            modelBuilder.Entity("CatchupService.Infrastructure.Persistence.SubscriptionConfigurationEntity", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AuthenticationParametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthenticationScheme")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CheckpointBatchSize")
                        .HasColumnType("int");

                    b.Property<bool>("ContinueOnParked")
                        .HasColumnType("bit");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long>("RequestTimeoutSeconds")
                        .HasColumnType("bigint");

                    b.Property<long>("RetryDelaySeconds")
                        .HasColumnType("bigint");

                    b.Property<int>("RetryMaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryIndexName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubscriptionId");

                    b.ToTable("SubscriptionConfigurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
